# Generated by Django 4.0.4 on 2022-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
