# Generated by Django 4.0.4 on 2022-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0009_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tehnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='')),
                ('description', models.TextField()),
            ],
        ),
    ]
