# Generated by Django 4.0.4 on 2022-06-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_tehnologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tehnologies',
            options={'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
    ]
