# Generated by Django 4.0.4 on 2022-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0011_alter_tehnologies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
        migrations.DeleteModel(
            name='Tehnologies',
        ),
    ]
